// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {generators} from '../models';

export function GeneratePassword(arg1:generators.GeneratePasswordInput):Promise<string>;

export function Greet(arg1:string):Promise<string>;
